name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build and Publish Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "latest"

      - name: Install dependencies
        run: bun install

      - name: Build the project
        run: bun run build

      - name: Compress dist folder
        run: zip -r tailwindcss-decompiler.zip dist/*

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: tailwindcss-decompiler.zip
